version: "3.9"
services:
  web:
    container_name: web
    image: caddy:2.3.0-alpine
    volumes:
      - ./site:/usr/share/caddy
      - ./data:/data
    ports:
      - 80:80
      - 443:443
    # command: caddy file-server --domain alecbrazeau.com
