# Generated by Django 3.0.4 on 2020-04-01 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(default='what-do-it-do?!', max_length=300, unique=True),
            preserve_default=False,
        ),
    ]
